name: workflows-demo
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    name: Run tests
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE_NAME: gh_ci_image
      DOCKERFILE_DIR: .ci/

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t $DOCKER_IMAGE_NAME $DOCKERFILE_DIR

      - name: Run tests from Docker container
        run: docker run --rm -v $PWD:/workspace -w /workspace $DOCKER_IMAGE_NAME:latest
