name: Lint ROS2 package
on:
  # Run this action whenever a pull request is made
  pull_request:
  push:
    branches:
      - master

jobs:
  # Note that we pass each job a different name to distinguish each linter job
  ament_lint_cpp:
    name: ament_${{ matrix.linter }}
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        linter: [clang_format, cpplint, xmllint]
    steps:
      - uses: actions/checkout@v3.0.0
      - uses: ros-tooling/setup-ros@0.3
      - uses: ros-tooling/action-ros2-lint@0.1
        with:
          linter: ${{ matrix.linter }}
          package-name: cpp_template_pkg
