name: Lint ROS2 package
on: [push, pull_request, workflow_dispatch]

jobs:
  # Note that we pass each job a different name to distinguish each linter job
  ament_lint_cpp:
    name: ament_${{ matrix.linter }}
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        linter: [clang_format, cpplint, xmllint, lint_cmake]
    steps:
      - uses: actions/checkout@v3.0.0
      - uses: ros-tooling/setup-ros@v0.3
      - uses: ros-tooling/action-ros2-lint@v0.1
        with:
          linter: ${{ matrix.linter }}
          package-name: cpp_template_pkg
